version: "3"
services:
  open-aps-db:
    image: open-aps-db:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${OPEN_APS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${OPEN_APS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${OPEN_APS_POSTGRES_DB}
      POSTGRES_REGISTER_PASSWORD: ${OPEN_APS_REGISTER_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${OPEN_APS_POSTGRES_USER} -d ${OPEN_APS_POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: -p ${OPEN_APS_POSTGRES_PORT}
