version: "3.5"
services:
  open-aps-db:
    build:
      context: ./open-aps-db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${OPEN_APS_POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${OPEN_APS_POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${OPEN_APS_POSTGRES_DB}
      POSTGRES_REGISTER_USER: ${OPEN_APS_POSTGRES_REGISTER_USER}
      POSTGRES_REGISTER_PASSWORD: ${OPEN_APS_REGISTER_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${OPEN_APS_POSTGRES_ADMIN_USER} -d ${OPEN_APS_POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: -p ${OPEN_APS_POSTGRES_PORT}
  open-aps-registration-site:
    build:
      context: ./registration-site
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_HOST: 'open-aps-db'
      POSTGRES_PORT: ${OPEN_APS_POSTGRES_PORT}
      POSTGRES_USER: ${OPEN_APS_POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${OPEN_APS_POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${OPEN_APS_POSTGRES_DB}
      APPLICATION_HOST: ${OPEN_APS_REGISTRATION_HOST}
      APPLICATION_PORT: ${OPEN_APS_REGISTRATION_PORT}
      OPEN_HUMANS_CLIENT_ID: ${OPEN_HUMANS_CLIENT_ID}
      OPEN_HUMANS_PROJECT_ADDRESS: ${OPEN_HUMANS_PROJECT_ADDRESS}
      OPEN_HUMANS_CLIENT_SECRET: ${OPEN_HUMANS_CLIENT_SECRET}
    ports:
      - ${OPEN_APS_REGISTRATION_PORT}:${OPEN_APS_REGISTRATION_PORT}
    command: ./wait-for-it.sh open-aps-db:${OPEN_APS_POSTGRES_PORT} -- ./entrypoint.sh

