version: "3.5"
services:
  open-aps-registration-site:
    restart: always
    command: ./entrypoint.sh
  open-aps-nightscout-ingester:
    restart: always
    environment:
      POSTGRES_HOST: ${OPEN_APS_POSTGRES_HOST}
      POSTGRES_PORT: ${OPEN_APS_POSTGRES_PORT}
      POSTGRES_USER: ${OPEN_APS_POSTGRES_NIGHTSCOUT_USER}
      POSTGRES_PASSWORD: ${OPEN_APS_NIGHTSCOUT_PASSWORD}
      POSTGRES_DB: ${OPEN_APS_POSTGRES_DB}
      OPEN_HUMANS_CLIENT_ID: ${OPEN_HUMANS_CLIENT_ID}
      OPEN_HUMANS_PROJECT_ADDRESS: ${OPEN_HUMANS_PROJECT_ADDRESS}
      OPEN_HUMANS_CLIENT_SECRET: ${OPEN_HUMANS_CLIENT_SECRET}
      INGEST_INTERVAL_HOURS: ${OPEN_APS_INGEST_INTERVAL_HOURS}
    command: ./entrypoint.sh
  open-aps-downloader:
    restart: always
    environment:
      POSTGRES_HOST: ${OPEN_APS_POSTGRES_HOST}
      POSTGRES_PORT: ${OPEN_APS_POSTGRES_PORT}
      POSTGRES_USER: 'ext_openaps_app'
      POSTGRES_PASSWORD: ${OPEN_APS_POSTGRES_EXT_OPENAPS_APP_PASSWORD}
      POSTGRES_DB: ${OPEN_APS_POSTGRES_DB}
      DOWNLOADER_APP_EMAIL: ${OPEN_APS_DOWNLOADER_EMAIL}
      DOWNLOADER_EMAIL_PASSWORD: ${OPEN_APS_DOWNLOADER_EMAIL_PASS}
      DOWNLOADER_SECRET_KEY: ${OPEN_APS_DOWNLOADER_SECRET_KEY}
      METABASE_SECRET_KEY: ${OPEN_APS_DOWNLOADER_METABASE_KEY}
      METABASE_URL: ${OPEN_APS_DOWNLOADER_METABASE_URL}
      DOWNLOADER_SLACK_KEY: ${OPEN_APS_DOWNLOADER_SLACK_KEY}
      DOWNLOADER_ADMIN_EMAIL: ${OPEN_APS_DOWNLOADER_ADMIN_EMAIL}
      DOWNLOADER_PUBLIC_URL: ${OPEN_APS_DOWNLOADER_PUBLIC_URL}
    command: ./entrypoint.sh
  metabase:
    restart: always
    environment: 
      MB_DB_TYPE: 'postgres'
      MB_DB_DBNAME: ${OPEN_APS_POSTGRES_DB}
      MB_DB_PORT: ${OPEN_APS_POSTGRES_PORT}
      MB_DB_USER: 'openapsuser'
      MB_DB_PASS: ${OPEN_APS_POSTGRES_METABASE_PASSWORD}
      MB_DB_HOST: ${OPEN_APS_POSTGRES_HOST}
  open-aps-etl:
    restart: always
    environment:
      POSTGRES_HOST: ${OPEN_APS_POSTGRES_HOST}
      POSTGRES_PORT: ${OPEN_APS_POSTGRES_PORT}
      POSTGRES_USER: 'ingestor'
      DOWNLOADER_SLACK_KEY: ${OPEN_APS_DOWNLOADER_SLACK_KEY}
      POSTGRES_PASSWORD: ${OPEN_APS_POSTGRES_INGESTOR_PASSWORD}
      POSTGRES_DB: ${OPEN_APS_POSTGRES_DB}
      ETL_INTERVAL_HOURS: ${OPEN_APS_ETL_INTERVAL_HOURS}
      OPEN_APS_OPENAPS_DEMOGRAPHICS_URL: ${OPEN_APS_OPENAPS_DEMOGRAPHICS_URL}
      OPEN_APS_NIGHTSCOUT_DEMOGRAPHICS_URL: ${OPEN_APS_NIGHTSCOUT_DEMOGRAPHICS_URL}
    volumes:
      - $PWD/credentials.json:/credentials.json
    command: ./entrypoint.sh
