version: "3.5"
services:
  open-aps-int:
    build:
      context: ./integration-tests
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: 'open-aps-db'
      POSTGRES_PORT: ${OPEN_APS_POSTGRES_PORT}
      POSTGRES_ADMIN_USER: ${OPEN_APS_POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${OPEN_APS_POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${OPEN_APS_POSTGRES_DB}
      POSTGRES_REGISTER_USER: ${OPEN_APS_POSTGRES_REGISTER_USER}
      POSTGRES_REGISTER_PASSWORD: ${OPEN_APS_REGISTER_PASSWORD}
    command: ./wait-for-it.sh open-aps-db:${OPEN_APS_POSTGRES_PORT} -- pytest

