version: "3.5"
services:
  open-aps-db:
    image: open-aps-db:latest
    ports:
      - 5423:5432
    volumes:
      - open-aps-postgres-data:/var/lib/postgresql/data
  open-aps-registration-site:
    image: open-aps-registration-site:latest
  open-aps-nightscout-ingester:
    image: open-aps-nightscout-ingester:latest

volumes:
  open-aps-postgres-data:

