AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  DbName:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: aurora-db-name
  DbMasterUsername:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: aurora-db-master-user
  DbMasterPassword:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: aurora-db-master-password


Resources:
  AuroraDbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for the OpenAPS Aurora DB. Created inside the default VPC"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 5432
        IpProtocol: tcp
        ToPort: 5432

  AuroraDB:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername: 
        Ref: DbMasterUsername
      MasterUserPassword:
        Ref: DbMasterPassword
      DatabaseName:
        Ref: DbName
      Engine: aurora-postgresql
      EngineMode: serverless
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 16
        MinCapacity: 2
        SecondsUntilAutoPause: 300
      VpcSecurityGroupIds: 
      - Fn::GetAtt: [ AuroraDbSecurityGroup, GroupId ]
