AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  MachineId:
    Description: The Amazon EC2 image ID used on the solution server.
    Type: AWS::EC2::Image::Id
    Default: ami-01e6a0b85de033c99
  SecurityKeyName:
    Description: The name of the AWS key pair to be used to access the instance.
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Description: The instance type of the openaps server
    Type: String
    Default: t2.nano
    AllowedValues:
      - t2.nano
      - t2.medium
      - t2.large
      - t2.xlarge
  VolumeSize:
    Description: The size (GB) of the underlying volume for the openaps server.
    Type: Number
    Default: 50
  ElasticIpAllocationId:
    Description: The allocation ID of the elastic IP to assign to the ec2 instance.
    Type: String

Resources:
  OpenApsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for the OpenAPS Nightscout data solution Machine. Created inside the default VPC"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443

  OpenApsServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref MachineId
      KeyName: !Ref SecurityKeyName
      InstanceType: !Ref InstanceType
      SecurityGroupIds: [!Ref OpenApsSecurityGroup]
      IamInstanceProfile : !Ref MyInstanceProfile
      BlockDeviceMappings:
        - 
          DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: !Ref VolumeSize
      Tags:
        - 
          Key: Name
          Value: open-aps-nightscout-data-server
        -
          Key: Owner
          Value: openaps.portal@gmail.com
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            apt-get update -y
            apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            apt-get update -y
            apt-get install -y docker-ce docker-ce-cli containerd.io awscli
            aws configure set region eu-west-1
            groupadd docker
            usermod -aG docker ubuntu
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            cd /home/ubuntu
            git clone https://github.com/mudano-data-solutions/open-aps-streaming.git
            cd open-aps-streaming/
            ./image-builds.sh
            ./run-production-application.sh 
  AssociateExistingIp:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !Ref ElasticIpAllocationId
      InstanceId: !Ref OpenApsServer

  OpenApsEc2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: 'IAM role allowing ec2 instances to read individual parameters from the param store'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AllowParamRead
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'ssm:GetParameter'
                Resource: '*'
              - Effect: Allow
                Action: 's3:GetObject'
                Resource: '*'

  MyInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      InstanceProfileName: 'OpenApsEc2InstanceProfile'
      Path: "/"
      Roles: 
        - 
          !Ref OpenApsEc2Role

Outputs:
  OpenApsElasticIp:
    Description: The elastic IP address assigned to the openaps server.
    Value: !Ref AssociateExistingIp

